# Generated by Django 2.2.5 on 2020-12-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=30, verbose_name='密码')),
                ('gender', models.BooleanField(default=False, verbose_name='性别')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
            ],
        ),
    ]
